defaults:
  - _self_
  - run_processor.yaml
  - viz: scenario

scores_path: ${paths.cache_path}/scores
features_path: ${paths.cache_path}/features

# General parameters
scenario_types:
  - gt
  # - ho # NOTE: currently not supported.
criteria:
  - critical_categorical
  # - critical_continuous
scores:
  - individual
  - interaction
  - safeshift
dpi: 300
output_dir: ${paths.cache_path}/analysis
add_timestamp: true
exp_tag: ""
total_scenarios: null

# Feature Analysis Parameters
show_kde: true
show_percentiles: true
individual_percentile_values: [10, 75, 90, 95, 99]
interaction_percentile_values: [10, 75, 80, 90, 95, 99]

# Score Analysis Parameters
tag: 'full'
test_percentile: 80 # Percentile to use to determine if holding out scenario for testing

# Scenario Visualization Parameters
percentiles:
  - 10
  - 50
  - 80
scenario_viz_dir: ${output_dir}/scenario_viz
viz_scored_scenarios: true
scores_tag: 'gt_critical_continuous'
score_to_visualize: 'safeshift'
organize_by_percentile: true
scenario_to_score_mapping_filepath: ./meta/scene_to_scores_mapping.csv
