_target_: characterization.datasets.amelia.AmeliaDataset
config:
  load: true
  ego_only: ${ego_only}
  seed: ${seed}
  scenario_type: ${scenario_type}

  parallel: ${parallel}
  batch_size: ${batch_size}
  num_scenarios: ${num_scenarios}
  num_workers: ${num_workers}
  num_shards: ${num_shards}
  shard_index: ${shard_index}
  step: ${step}
  total_steps: 60

  airports: ${paths.airports}

  scenario_base_path: ${paths.scenario_base_path}
  scenario_meta_path: ${paths.scenario_meta_path}
  conflict_points_path: ${paths.output_paths.conflict_points_cache_path}
  conflict_points:
    intersection_threshold: 0.5 # meters
    resample_factor: 3

  closest_lanes_path: ${paths.output_paths.closest_lanes_cache_path}
  closest_lanes:
    num_lanes: 16
    threshold_distance: 10 # meters
    subsample_factor: 2
